---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/klintwal/public_html
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp contact-me.html $DEPLOYPATH
    - /bin/cp portfolio.html $DEPLOYPATH
